### ISSUE TITLE
[Feature Request] Store finished print time so it is 100% accurate next time the file is printed

### ISSUE THREAD

**Issue by IntegersOfK** [eyal0/OctoPrint-PrintTimeGenius#110]
This is a feature request. After my print is finished it would be nice if the plugin could store a little data somewhere next to the file with the record of how long it actually took to print. The next time I print that same file, I can know the exact time it will take to print without any estimation.

**Comment by eyal0** [comment]
OctoPrint already does this.  The "Print Time" in the top-left is the estimation unless there has been a successful print in which case it is the most recent success.
![](https://octoprint.org/assets/img/features/temperature-tab.png)

**Comment by IntegersOfK** [comment]
Wow great, I didn't know that. Thank you very much.
