### ISSUE TITLE
Does PTG take into account M201 commands?

### ISSUE THREAD

**Issue by MasterPIC** [eyal0/OctoPrint-PrintTimeGenius#117]
Hi,
I know that PTG takes into account Marlin based printer report and also M201-M204 commands.
But does it take into account only the first M201-M204 commands eventually used to set the printer?
Or does it take care of several M201-M204 commands eventually used inside the gcode file?

Thanks
Armando

**Comment by eyal0** [comment]
It will take both into account.  The Mcodes that are on the command line and the Mcode that are in the file are treated the same: They are processed in the order that they are seen.  The command-line is processed before the input file.

I hope that helps!  Re-open this if you see problems with it.

**Comment by MasterPIC** [comment]
Thanks!
