### ISSUE TITLE
Add a version check somewhere

### ISSUE THREAD

**Issue by eyal0** [eyal0/OctoPrint-PrintTimeGenius#12]
This plugin requires at least 1.3.9

**Comment by jneilliii** [comment]
Can't you do this within setup.py for pip installs [here](https://github.com/OctoPrint/Plugin-Examples/blob/b04aa440848e3072b7e62f75ed0a0f0a82333859/helloworld/setup.py#L36)?  I've never tried it but I think it's something like octoprint>1.3.8 maybe?  Sorry not much help here.

It also is an option when submitting the plugin repo for publishing I believe in the compatibility section, which looks like you have in 1.3.9rc1, which might should just be 1.3.9?

**Comment by eyal0** [comment]
Done in 7098f10
