### ISSUE TITLE
REALLY inaccurate print remaining time

### ISSUE THREAD

**Issue by NovaViper** [eyal0/OctoPrint-PrintTimeGenius#126]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.3.11

PrintTimeGenius Version (if you know): 1.3

What did you try: Slicing and upload my file into Octoprint, then made it run immediately after doing so

What happened: For some strange reason, the print time estimate didn't load up at first, giving me a red dot then it suddenly showed a green dot and said 9 hrs and 58 minutes for the remaining time left while it was printing out the first layer. Even now up on the 4th layer it still says 6 hours.

What did you expect to happen: It should be around 2 hrs, ever other analizer (Slic3r PE/PrusaSlic3r and the online gcode viewer) all say it should be around 2 hrs.

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).
Log: [plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/3198096/plugin_PrintTimeGenius_engine.log)
Gcode: [Ender3_SKR_V13_Lower_PLA0.24mm.txt](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/3198105/Ender3_SKR_V13_Lower_PLA0.24mm.txt)

**Comment by eyal0** [comment]
```
2019-05-20 07:43:01,230 Probably started printing, aborting: '"/home/pi/oprint/bin/python2" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" marlin-calc "/home/pi/.octoprint/uploads/BoardMod/Ender3_SKR_V13_Lower_PLA0.24mm.gcode" "M200 D1.75
M200 D0
```

You can see that PTG aborted because you started printing before it was done working.  You can either wait longer for PTG to finish or you can allow PTG to work while printing.  That's in the options.
