### ISSUE TITLE
SyntaxError on Python 3

### ISSUE THREAD

**Issue by Steeven9** [eyal0/OctoPrint-PrintTimeGenius#180]
OctoPrint Version: 1.4.0rc4 on win7 32bit, python 3.8.1

PrintTimeGenius Version (if you know): latest from the GitHub link

What did you try: Install the plugin via the GitHub URL

What happenned: Python 3 gives a SyntaxError

What did you expect to happen: a successful installation

Below is the installation log with the error:
[log.txt](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/4150251/log.txt)

**Comment by eyal0** [comment]
Maybe this?

https://stackoverflow.com/questions/32386469/logging-module-not-working-with-python3

What did octoprint do to solve this problem?

**Comment by eyal0** [comment]
Fixed by #178 ?

**Comment by Steeven9** [comment]
Can confirm, successful install.
Thank you very much!

**Comment by eyal0** [comment]
On version 2.2.1? Hooray!

**Comment by Steeven9** [comment]
Yup, version 2.2.1 running on OctoPrint 1.4.0rc4, win7 32bit, python 3.8.1. 
Good job!
