### ISSUE TITLE
change info loop delay

### ISSUE THREAD

**Issue by theuncle** [eyal0/OctoPrint-PrintTimeGenius#181]
Some time ago I've achieved to change the info loop delay, modifiying the config.yaml. I'm pretty shure this setting was in this file but not anymore.
I can´t find the line to modify. Is it possible that I'm confusing the file?

**Comment by eyal0** [comment]
I don't understand.  Which info loop delay do you mean?

**Comment by eyal0** [comment]
Long time no answer.  Re-open and clarify if you want.
