### ISSUE TITLE
Request: option to disable gold star

### ISSUE THREAD

**Issue by timur-tabi** [eyal0/OctoPrint-PrintTimeGenius#183]
Please add an (advanced) option to disable the gold star.  I can see now that PrintTimeGenius is working.  I don't need a gold star next to every file name any more.

**Comment by kantlivelong** [comment]
+1

**Comment by jneilliii** [comment]
+1

**Comment by jneilliii** [comment]
+1

**Comment by eyal0** [comment]
Can you test this please?  You can install this in OctoPrint using the normal plugin installation method with this link:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/showStars.zip

The option is in the settings dialog.

**Comment by timur-tabi** [comment]
I only have one file in my queue, but this version does appear to work.  The gold star is gone.  Thanks.

**Comment by jneilliii** [comment]
I can confirm @eyal0 this version does allow for removing the star (thanks so much) and did resolve the issue with 1.4.1RC2.
