### ISSUE TITLE
python3 - marlin-calc.armv71 not executable

### ISSUE THREAD

**Issue by MarekKrzyszton** [eyal0/OctoPrint-PrintTimeGenius#188]
OctoPrint Version: 1.4.0 (on Octopi/rpi 3B+)
PrintTimeGenius Version (if you know): 2.2.1

What did you try: moved OctoPrint to python3

What happenned (log):
```
Exception: Running: "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintTimeGenius/analyzers/marlin-calc.armv7l" "/home/pi/.octoprint/uploads/CE3_MakerBot_Headphone_Stand.gcode"
Not executable: /home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintTimeGenius/analyzers/marlin-calc.armv7l

```

chmod +x marlin-calc.armv7l 
solved the problem

just letting know
cheers

**Comment by eyal0** [comment]
I just redownloaded the zip file and it looks fine to me:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/2.2.1.zip

Are you sure?

**Comment by MarekKrzyszton** [comment]
Hi,
I have installed plugin through Plugin Manager.
Perhaps it's python3 related, that's why mentioned

This is what I see after ls -al (marlin-calc.armv71 has been modified by me):
![image](https://user-images.githubusercontent.com/50481193/82646417-e1375400-9c14-11ea-8239-dbf4bf69b435.png)

**Comment by eyal0** [comment]
I am using python3.  I tried uninstalling and reinstalling a few times in the normal way and everything seems fine.  Could you try to download that zip file mentioned above to your OctoPi and unzip it and see if the file permissions are correct?

**Comment by marekorok** [comment]
Hi,
yes - checking the zip seems attributes is correct.

![obraz](https://user-images.githubusercontent.com/28598034/82951427-691bb600-9fa7-11ea-9b0b-3dc34b012daf.png)


I have reinstalled once again, checked that all files are removed.
Installed from the above url, the same result... 
![obraz](https://user-images.githubusercontent.com/28598034/82951284-2659de00-9fa7-11ea-82c3-156690ae2aed.png)

If no one else complains I can live with that, not a big deal.

**Comment by MarekKrzyszton** [comment]
Hi,
yes - checking the zip seems attributes are correct.

![obraz](https://user-images.githubusercontent.com/28598034/82951427-691bb600-9fa7-11ea-9b0b-3dc34b012daf.png)


I have reinstalled once again, checked that all files are removed.
Installed from the above url, the same result... 
![obraz](https://user-images.githubusercontent.com/28598034/82951284-2659de00-9fa7-11ea-82c3-156690ae2aed.png)

If no one else complains I can live with that, not a big deal.

**Comment by eyal0** [comment]
It's weird.  No one else has mentioned it.  I guess that you could dig into your OctoPrint and see how it is running.  Maybe in the logs there is some clue, like the user that installs isn't the same as the user that runs it?

Do you have a umask configured somewhere?

https://unix.stackexchange.com/questions/166948/why-is-my-pip-installed-python-script-not-executable-for-everyone
