### ISSUE TITLE
Getting in contact with the developer (Eyal0)

### ISSUE THREAD

**Issue by AlbertMN** [eyal0/OctoPrint-PrintTimeGenius#208]
Hi there. Sorry for opening an issue regarding this, but I simply couldn't find _any_ contact info on the developer anywhere else, and as you aren't on the OctoPrint community forums, or the Discord server (under the same name, at least), I thought this was worth a try :D

So @eyal0, I'd love to get in contact with you - would you mind sending me an email at albert@simplyprint.dk, or give me some contact-info? :)

Thanks!

**Comment by eyal0** [comment]
I wrote you.

**Comment by AlbertMN** [comment]
Responded - having some issues with our mail-server lately though, so did you receive my reply?
