### ISSUE TITLE
Install problem on Octopi

### ISSUE THREAD

**Issue by pjrestrepo** [eyal0/OctoPrint-PrintTimeGenius#226]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Not found.

Please fill this out:

OctoPrint Version:
1.5.2 (Python 3)

PrintTimeGenius Version (if you know):
2.2.7

What did you try:
Installed with:  pip install "https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/master.zip" 

What happenned:
![image](https://user-images.githubusercontent.com/10343732/103295154-fd744e00-49b8-11eb-902e-e46db5b53ff3.png)

What did you expect to happen:
I expected it to install without any errors.

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).
No log. Did not install...

**Comment by eyal0** [comment]
That's an uncommon way to install. Most people install from within OctoPrint's plugins menu. Can you try it that way?

It looks like you might be trying to install without first having activated the OctoPrint virtual environment.

**Comment by pjrestrepo** [comment]
Thank you very much Eyal. It installed without any problem from within
OctoPrint.

Thank you for a very useful plugin, best regards, and a Happy New Year!

Pedro

**Comment by eyal0** [comment]
No problem. Enjoy!
