### ISSUE TITLE
Total Time: inf

### ISSUE THREAD

**Issue by terri913** [eyal0/OctoPrint-PrintTimeGenius#230]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.5.3

PrintTimeGenius Version (if you know): 2.2.7

What did you try:

What happenned: Not working
[plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/5896488/plugin_PrintTimeGenius_engine.log)
[bob_bot.txt](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/5896502/bob_bot.txt)

What did you expect to happen:

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).

**Comment by eyal0** [comment]
The problem is due to the M203 line in the log.  It says that the maximum rate of extrusion is 0.  Can you type M503 on your printer and post that output.  Do you have `M205 E0` in your M503 output?

Sorry to have kept you waiting.

**Comment by terri913** [comment]
Thanks so much for replying.

It is working perfectly now so I don’t know why it was having a problem before.

It is really cool of you to take the time to help me. And it’s a great plugin.

**Comment by eyal0** [comment]
Glad to hear it.  Enjoy!
