### ISSUE TITLE
Estimates suddenly wrong

### ISSUE THREAD

**Issue by Jack77777777** [eyal0/OctoPrint-PrintTimeGenius#250]
Did 503 before upload and analyze. Estimated time was over 6h. after printing in 3:38h estimate shows now 5+h but still way to wrong.
![image](https://user-images.githubusercontent.com/64719909/114422928-fdd6d480-9bb6-11eb-882f-1d126c95037b.png)
![image](https://user-images.githubusercontent.com/64719909/114422985-0a5b2d00-9bb7-11eb-9dc9-3d797ae7d3ef.png)
[plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/6298024/plugin_PrintTimeGenius_engine.log)
[Makita_Battery_New.zip](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/6298030/Makita_Battery_New.zip)

**Comment by eyal0** [comment]
It seems that you had some recent prints that were much faster than predicted so PTG has adjusted.

Can you look in the advanced settings to see them?  If you delete them and then re-analyze the file, you will get a better result.

```
2021-04-12 11:47:30,559 Time spent printing, actual vs predicted: 12704.528058577998/12724.484557649725, 7098.386946807/18643.968241987117, 1569.4977473090003/4676.17500838264, 367.7750795760003/1300.4533922820253, 4728.910934346997/12855.435260625782
2021-04-12 11:47:30,565 Average scaling factor: 0.5272674592345831
```

This is in the file that you sent me.  See how it has scaled the time by 0.52?  That's is 52%, so the estimate will be 52% of actual.

**Comment by eyal0** [comment]
I just added more info here: https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

**Comment by Jack77777777** [comment]
Does PTG notice a cancelled print or does it mean was finished faster then expected?

**Comment by eyal0** [comment]
I don't even remember.  I think that it only looks at completed prints.  If you notice a different behavior, I can try to fix it.

(I developed this plugin back when I owned a 3d printer.  I haven't owned one for 3 years now so testing is made difficult.)

**Comment by Jack77777777** [comment]
Deleted compensation values and reanalyzes all gcodes. Looks good so far.

**Comment by eyal0** [comment]
Any guess what might have cause PTG to think that the print took less time than predicted?  Did you cancel a print mid-way?

**Comment by Jack77777777** [comment]
I cancelled a job several minites after start due to Adhesion problems 🙈

**Comment by eyal0** [comment]
Hm, that is surprising to me.  In the code, I am only recording into the print_history when the event is `PrintDone`:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/blob/master/octoprint_PrintTimeGenius/__init__.py#L474

And according to the documentation, `PrintDone` should only happen when a print is completed successfully.

https://docs.octoprint.org/en/master/events/index.html#printing

Yet you saw print history being recorded even when the print was cancelled.  Are you sure that the print history was written even when you cancelled the print?  If you can confirm this then I can see what the problem is.  Maybe the issue is in OctoPrint and not in PTG?

**Comment by Jack77777777** [comment]
> Are you sure that the print history was written even when you cancelled the print?  If you can confirm this then I can see what the problem is.  Maybe the issue is in OctoPrint and not in PTG?

Where can i check this?

**Comment by eyal0** [comment]
Start a print, wait a few minutes, cancel it in the middle, and let me know if it put a row in the print history table or not.

Then do it again with a print that you *don't* cancel in the middle and see if it puts a row in the print history table.

The table is viewable in the settings, like before.

That would prove one way or another if cancelled prints are getting added to the print history table.  I think that it would work!

**Comment by Jack77777777** [comment]
Do you mean if it adds a row to https://plugins.octoprint.org/plugins/PrintJobHistory/ ?
I have enabled to save only successful jobs in https://plugins.octoprint.org/plugins/PrintJobHistory/

**Comment by eyal0** [comment]
No, I mean the print history that PrintTimeGenius maintains inside of the PrintTimeGenius Advanced Settings.  It's only supposed to save on success but I don't know if it does that correctly and I'm curious to know.  In my testing it works fine but maybe you saw a different behavior that led to this bug report?

**Comment by Jack77777777** [comment]
I did a snapshot of compansation values, cancelled a print and did another snapshot. Both have the same values.

Before Cancel:
![Before_Cancel](https://user-images.githubusercontent.com/64719909/115817076-6cf3ca80-a3fa-11eb-8f6d-6d277629a205.png)

After Cancel:
![After_Cancel](https://user-images.githubusercontent.com/64719909/115817096-741ad880-a3fa-11eb-999a-481824690190.png)

**Comment by eyal0** [comment]
So it looks like everything is working okay now.  If you see more issues, go ahead and file a bug.

It's odd to me the words on your screen.  Does "Geasmt" mean "total" in English?  I guess that it translated only one word!  Surprising to me.

I'm also excited to see how good the predictions are.  Extruding prediction is very high quality.  I'm glad that my plugin is working.

**Comment by Jack77777777** [comment]
Yes, Gesamt is german and means total. I think you can close this one. 

Thanks a lot for your effort and support.
