### ISSUE TITLE
Model height wrong

### ISSUE THREAD

**Issue by Jack77777777** [eyal0/OctoPrint-PrintTimeGenius#253]
**Describe the bug**
If PrintTimeGenius is activated the height is wrong in web Ui and .metadata.json. If i deactivate PrintTimeGenius .metadata.json and Web Ui has the right data.

**To Reproduce**
1. Delete .octoprint/uploads/.metadata.json 
2. Activate PrintTimeGenius
3. Upload Gcode
4. Result:
![image](https://user-images.githubusercontent.com/64719909/117789508-b50f4b80-b248-11eb-9795-209749a87d1e.png)
![image](https://user-images.githubusercontent.com/64719909/117790614-d1f84e80-b249-11eb-8891-00d21ceb4908.png)

5. Delete .octoprint/uploads/.metadata.json and Gcode
6. Deactivate PrintTimeGenius 
7. Upload same Gcode
8. Result:
![image](https://user-images.githubusercontent.com/64719909/117789691-e2f49000-b248-11eb-9d1d-b48eb5acd8c8.png)
![image](https://user-images.githubusercontent.com/64719909/117790254-775ef280-b249-11eb-9291-436c84cec32f.png)

**Expected behavior**
8.

**OctoPrint Version:**
1.6.1

**PrintTimeGenius Version (if you know):**
2.2.7

[Nut.gcode.txt](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/6457911/Nut.gcode.txt)
[plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/6457916/plugin_PrintTimeGenius_engine.log)

**Comment by eyal0** [comment]
I see that PTG reports the "height" as "maxZ" minus "minZ", which is indeed 9.8mm.  Is it better to report 10mm?  I suppose so because that min height of 0.2mm is just the thickness of the layer.  I guess that for height I could just always report maxZ?

I'm also not accounting for nozzle thickness, I guess technically we should also be reporting X and Y to be enlarged by the thickness of the nozzle.  Ah well, no big deal.

**Comment by eyal0** [comment]
Here's where things went wrong: https://github.com/OctoPrint/OctoPrint/commit/4c4570e2e168acedd91c67a68c1ba5e7748d5830

Maybe the heights reported by PTG and OctoPrint's built-in analyzer used to match before this change.  I can make the same change.

**Comment by Jack77777777** [comment]
Yes, that's it. This is the reason why i referenced this issue there. I opened both issues. As OP is fixed now you have to match your code 😁.

**Comment by eyal0** [comment]
If you'd like to look at the PR, be my guest.  If you want to download it, install this at a plugin:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/refs/heads/bedZ.zip

You will need to re-analyze files for it to take effect.

**Comment by Jack77777777** [comment]
I will test tomorrow due to a ongoing print.

**Comment by Jack77777777** [comment]
Tested and confirm it is working.

Thanks a lot
