### ISSUE TITLE
Feature Request - Analyze Button

### ISSUE THREAD

**Issue by the0remora** [eyal0/OctoPrint-PrintTimeGenius#255]
I use SSH to upload my gcode this means that PrintTimeGenius does not automatically calculate the print time. Every time I have to go in to settings => Plugins => PrintTimeGenius find the gcode file in that list and hit analyze. Could an Analyze Button be added to the File Browser in the main window please?

**Comment by eyal0** [comment]
Are you uploading into the correct folder? You should be uploading into the watched folder and not into the uploads folder.

**Comment by the0remora** [comment]
I did not know that folder existed. Thank you.

**Comment by eyal0** [comment]
Most people don't know about that folder!  I wish that more people did.  Maybe there ought to be a `README` file in the uploads folder explaining it.
