### ISSUE TITLE
[Request] Exclude files on SD card and/or make gcode filelist bigger

### ISSUE THREAD

**Issue by Gathaeryx** [eyal0/OctoPrint-PrintTimeGenius#256]
The filelist in the plugin window is extremely small, and since there are only 5 lines to display, there is a lot of clutter from the files on my SD card, which can't be analyzed. It would be nice to either be able to make this window bigger, or to be able to exclude the SD card files to show up.

![image](https://user-images.githubusercontent.com/63103581/119505980-c474b580-bd6d-11eb-93d5-4aabde5776a6.png)

**Comment by eyal0** [comment]
Hmm, yeah, that could be a good idea.  Because the files that are on the sdcard can't be analyzed anyway.  Okay, that should be easy, I think.

**Comment by eyal0** [comment]
I haven't any way to test it.  Can you test it for me?  Please install this from the plugin settings within OctoPrint:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/refs/heads/exclude_sd_card.zip

And then check the list with the same SD card as before and see if it looks right to you.

Thanks!

**Comment by Gathaeryx** [comment]
Sorry for the (extremely) late reply, but I just checked the new plugin, and the files on the SD card are indeed missing. Thanks! This makes it a lot easier to see which files still need analysing.

**Comment by eyal0** [comment]
Fixed by #257
