### ISSUE TITLE
[Feature Request] - Show estimated time until next User Interaction is required

### ISSUE THREAD

**Issue by schleifi** [eyal0/OctoPrint-PrintTimeGenius#274]
Hi,

it would be great if the tool could also calculate the time when the next user interaction (like a filament change or just a printing pause for inserting objects) is required.
For the Prusa Mini, the gcode command is M600 or M601 (but I guess it would be better if the user would have a field where to input custom gcode commands).
The plugin then not only shows the total estimated running time, but also the times when such commands are expected to be executed. That would be a great help for planning the printing with filament changes etc.

**Comment by eyal0** [comment]
Check this out: https://plugins.octoprint.org/plugins/TimeToFilament/

Re-open this bug if you have troubles with it.
