### ISSUE TITLE
Cant find in Plugin Manager nor install manually

### ISSUE THREAD

**Issue by jonathanlundstrom** [eyal0/OctoPrint-PrintTimeGenius#29]
Hi,

I would love to try this plugin but unfortunately I can't find it in the Plugin Manager. I can't install it manually from the provided URL either, when I do so, it says plugin "Unknown" installed and the plugin is nowhere to be found in the UI.

I'm running the latest stable OctoPrint (1.3.8).

Thanks,
Jonathan

**Comment by mark-hahn** [comment]
Same here but getting `Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-bzPGDs/`

**Comment by eyal0** [comment]
@Tinchus2009 That is also due to being on an old OctoPrint. I'm surprised that you were able to install at all. The latest release doesn't even let you install with old OctoPrint. Maybe you installed an old release?

**Comment by Tinchus2009** [comment]
@eyal0 Old? Mine is 1.3.8.... it is latest available

**Comment by eyal0** [comment]
@Tinchus2009 1.3.8 is the latest stable.  This plugin is developed for 1.3.9, which is still the unstable version.  In your settings, you can switch from stable to development, if you want.  But it might be less stable for you.

![octoprint_tracking_development](https://user-images.githubusercontent.com/109809/42742604-a8e69440-88c4-11e8-9b13-a6924b7f92da.png)

**Comment by Tinchus2009** [comment]
ok... no thanks, I refer to stay in "stable"version. Maybe you should mark this plugin to be used only in that version so pleople dont get confused

**Comment by eyal0** [comment]
I did mark it that way, but despite the marking, it gets offered to people!  I think that OctoPrint doesn't know how to distinguish.

You can try restarting OctoPrint in safe mode and then try to remove the plugin.
