### ISSUE TITLE
Does this plug-in work using Klipper?  M503 command not recognized?

### ISSUE THREAD

**Issue by bginvestor** [eyal0/OctoPrint-PrintTimeGenius#297]
I am running the latest version of Octoprint / Klipper on an Ender3 .   At the Octoprint terminal, klipper does not recognize the M503 command as suggested in the readme.   Will this plug-in still work for my configuration?   Thank you.

**Comment by eyal0** [comment]
It doesn't work with Klipper really. The M503 tells the plugin how to calculate time precisely. Without, it calculates with defaults which is not as good.

I tried to add Klipper support a long while ago but I couldn't figure it out and I didn't get the support needed on the Klipper side, either, so I gave up.
