### ISSUE TITLE
Mttq plugin is reporting the original progress percentage

### ISSUE THREAD

**Issue by standardgbg** [eyal0/OctoPrint-PrintTimeGenius#298]
Hi,

I use PrintTimeGenius and its genius ;)
But the mttq plugin for octoprint seems to report the original non-genius progress percentage. For example the value displayed in octoprint UI and on the printer display is 78%, but the progress reported by the mttq plugin is 69%.
The mttq plugin has the possibility for other plugins to send other values over mttq.
Is this something that could be added to the PrintTimeGenius plugin?

Here is a link to to the issue reported by another user in the mttq page:
https://github.com/OctoPrint/OctoPrint-MQTT/issues/103

(I use version 2.3.0)

**Comment by eyal0** [comment]
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems#the-progress-bar-doesnt-match-the-progress-reported-in-my-other-plugin

Reopen this if it doesn't answer your question.
