### ISSUE TITLE
Percentage shown "12.96omplete" not "12% complete" or "12.69% complete"

### ISSUE THREAD

**Issue by tehniq3** [eyal0/OctoPrint-PrintTimeGenius#302]
On ANET A8 LCD 2004 display:
![IMG_20230331_145046](https://user-images.githubusercontent.com/4947574/229125611-d46c8de4-3eb4-4b56-80eb-aa1278e42f44.jpg)

I think a INT variable is enough, but is just my oppinion !

**Comment by eyal0** [comment]
Is this a bug in PTG?  When you disable PTG, does this bug go away?

**Comment by tehniq3** [comment]
if not use your plugin, on last row of display printer not show any info, but if printer is not connected to Octoprint show "Printing  12%"

**Comment by tehniq3** [comment]
I think that is an issue from other plugin ... sorry for my mistake.. you can close the post...

**Comment by tehniq3** [comment]
sorry for my mistake, other plugin is responsable for issue !

**Comment by eyal0** [comment]
I can probably guess the reason that you are having a problem.

In the other plugin where it says "%" in the code or in the configuration, it should say "%%". The "%" is special and it must appear twice.

**Comment by tehniq3** [comment]
you are right ! instead one % I put %%% 😎 I need to change in {completion:.2f}%%% done to see "16.4% done"
![rezultat_bun_niq_ro_Anet_A8](https://user-images.githubusercontent.com/4947574/229372954-82aae827-757d-4399-a267-ab2fb7cea91d.jpg)
PS: many thank to you... nota some beer from my side ! 🤘🍺🍺🍺
