### ISSUE TITLE
Question: analysisPrintTime vs. estimatedPrintTIme vs. other time estimates in the gcode

### ISSUE THREAD

**Issue by puterboy** [eyal0/OctoPrint-PrintTimeGenius#310]
I am trying to understand the difference between at least 4 different notions of printTime.
1. estimatedPrintTime field in .metadata.json (is this the estimate that Octoprint itself creates?)
2. analysisPrintTime field in .metadata.json (I assume this is the output of your algorithm)
3. The print time encoded by Prusa Slicer in the gcode file name (e.g., Body1_0.3mm_PLA_MK3S_8m.gcode) (I assume this is based on Prusa Slicer's estimation of the print time though it differs from #1 & #2)
4. ";estimated printing time (normal mode)" added to the gcode file itself by Prusa Slicer (this seems to be about 2 minutes longer than 3 - is this because it includes the auto-bed leveling time?)
5. ";estimated printing time (silent mode)" added to the gcode file itself by Prusa Slicer (this is understandably a little longer than 4)

Thanks

**Comment by eyal0** [comment]
Comments in the gcode are processed by this script: https://github.com/eyal0/OctoPrint-PrintTimeGenius/blob/master/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py

If we're not using the comments then we process then `marlin-calc` processes the gcode and runs a simulation to find the print time.

Either of those make the `analysisPrintTime`.  That comes from the file.

After that, we might adjust it based on five most recent prints.  The adjustment is meant to compensate for heating time, cooling time, and any inaccuracies in the simulation.  The result of that is the `estimatedPrintTime`.
