### ISSUE TITLE
OctoPrint 1.3.9rc3 compatibility ?

### ISSUE THREAD

**Issue by vincent-ogury** [eyal0/OctoPrint-PrintTimeGenius#32]
The RC3 is out with a fix for the estimated time.
I have seen a monkeypatching for this part.

Does anyone has try this module again the rc3 ?
Is it still working even with the monkey patching ?

**Comment by eyal0** [comment]
The monkey patching is only for 1.3.9rc2, you can see here where I check the version:

https://github.com/eyal0/OctoPrint-PrintTimeGenius/blob/master/octoprint_PrintTimeGenius/__init__.py#L318

rc3 fixed the problem so it doesn't need the patch.  I just checked it and it's working fine.

I'll leave the code in for people that are still on 1.3.9rc2.

**Comment by vincent-ogury** [comment]
I can confirm the plugin works properly !
