### ISSUE TITLE
Caused severe stuttering

### ISSUE THREAD

**Issue by Crowlord** [eyal0/OctoPrint-PrintTimeGenius#34]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.3.0RC3 also 1.3.8 (downgraded to test however plugin not visible)

PrintTimeGenius Version (if you know):1.0.6

What did you try: Printing a large complicated model sliced in S3D (64mb filesize)

What happenned: Comms lag resulting in a stuttering print and artifacts on perimeters. pi temp was higher then expected (normally runs at max 70c in this weather was running at 80c) CPU was at around 45% load

Rerunning the print now with plugin disabled no issues and running at 70c and 35% load

What did you expect to happen: Usual reliable print (model is a shop item that has printed over 10 time previously;y on this slice with no issues)

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).

**Comment by eyal0** [comment]
Interesting. Maybe the analysis program is running while the object is printing and it's causing major lag?

If you have debugging on while you print, you can see when the analysis starts and ends and when the printing is running, to see if they overlap.

I will look into cancelling analysis while printing.
