### ISSUE TITLE
Weird char instead of gold star

### ISSUE THREAD

**Issue by vincent-ogury** [eyal0/OctoPrint-PrintTimeGenius#36]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.3.9rc3

PrintTimeGenius Version (if you know): 1.0.5

What did you try:
Print

What happenned:
The gold star is badly display

What did you expect to happen:
A real gold star

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).

Can you use the html code instead of the utf8 (I guess) one ?
This code for instance: &#x2606;

![star](https://user-images.githubusercontent.com/19665868/42843146-81151d46-8a0f-11e8-9c31-83c0cffe68d0.png)

**Comment by eyal0** [comment]
I did that in version 1.0.6. Please let me know if that works for you.

**Comment by vincent-ogury** [comment]
Ok thanks.

I will check on my next print (long running print in progress ;))

**Comment by vincent-ogury** [comment]
fixed
![star](https://user-images.githubusercontent.com/19665868/42900785-08d49e36-8aca-11e8-9809-2a5b2d3b969b.png)
