### ISSUE TITLE
no output 1.3.9rc3

### ISSUE THREAD

**Issue by kjkroeker** [eyal0/OctoPrint-PrintTimeGenius#44]
Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.3.9rc3

PrintTimeGenius Version (if you know):1.0.7

What did you try: analyze file from settings

What happened: nothing, but log shows normal execution and I can execute the commands in a shell

What did you expect to happen:  results to appear in the settings window

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).

**Comment by eyal0** [comment]
Analyzing doesn't put the results in the settings window.  It just analyzes and writes to the log.

Are you saying that you wish that the analyzer put some results into the settings window?
