### ISSUE TITLE
Enhancement request: Project what local time the print will complete

### ISSUE THREAD

**Issue by thehammer2** [eyal0/OctoPrint-PrintTimeGenius#48]
No issue here, just a simple quality-of-life enhancement request.

Have the plugin add what it calculates as the projected time to complete the print to the current local time and reports a projected local time that completion will occur at.  Bonus points if you can find some way to poll a timeserver during analysis to correct the device's clock to current universal time and then correct for a time zone the user selects from within the plugin settings.

EDIT: It just occurred to me that a lot of users don't have their devices facing the internet, so the time server idea might be bunk.  Maybe read the current time from the device's clock and have a place where the user can see it and manually input their local time to reset the clock, if needed, so the projected completion time is correct for them.

**Comment by eyal0** [comment]
Have you considered this: https://plugins.octoprint.org/plugins/octoprint-eta/

or this: https://plugins.octoprint.org/plugins/detailedprogress/

**Comment by thehammer2** [comment]
I'm unsure exactly how PrintTimeGenius interacts with the rest of the OctoPrint system. Will those plugins use PrintTimeGenius's estimates to display their ETA? If so, then that's exactly what I'm looking for.

**Comment by eyal0** [comment]
Yes, they will.  PrintTimeGenius replaces that estimated print time and also the remaining print time calculations.  Plugins that use those will use the new values.  Should work together great!

**Comment by thehammer2** [comment]
Outstanding, then. Thanks again.

I'll go ahead and close this issue.
