### ISSUE TITLE
Fails to analyse the gcode

### ISSUE THREAD

**Issue by glena** [eyal0/OctoPrint-PrintTimeGenius#69]
OctoPrint Version: `OctoPrint 1.3.9 running on OctoPi 0.15.1`

PrintTimeGenius Version (if you know): `1.1.5`

What happenned: Run several prints and it never showed the `Approx. Total Print Time` nor the gold star. Also run the gcode analysis and it does not show any result.

Log:
[plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/2283000/plugin_PrintTimeGenius_engine.log)

**Comment by glena** [comment]
Ah missed that setting, is it possible to add some kind of feedback when the analysis is running?

Let me check.

**Comment by glena** [comment]
That was it. Sorry for the fake issue :P
good job with the plugin BTW

**Comment by eyal0** [comment]
This is fixed by #70 and #83 and #91
