### ISSUE TITLE
Stars are misaligned in FileManager

### ISSUE THREAD

**Issue by DominikPalo** [eyal0/OctoPrint-PrintTimeGenius#93]
OctoPrint Version: 1.3.9
PrintTimeGenius Version: 1.2
FileManager Version: 0.1.3

I don't really know if this issue is more related to the [FileManager](https://github.com/Salandora/OctoPrint-FileManager) plugin or to the PritTimeGenus plugin, but when I have installed both of them, files in [FileMananager](https://github.com/Salandora/OctoPrint-FileManager) are displayed as you can see on the screenshot (the star icons are misaligned):

![image](https://user-images.githubusercontent.com/1623257/47106456-d9e4e300-d246-11e8-824d-516393c0d17d.png)

It is possible to somehow fix it? Or should it be reported to the FileManager project?

**Comment by eyal0** [comment]
I think that this is due to an unfortunate interaction between File Manager and my plugin.  I set it up so that the gold star appears right after the gcode filename.  Maybe the best solution is to make it so that it only appears outside the File Manager and not in the File Manager window?

**Comment by eyal0** [comment]
I'll need to install File Manager to test it.

**Comment by eyal0** [comment]
Okay, I trust you!  I'll patch it in and release it soon.
