### ISSUE TITLE
[Feature Request]  Add analyze now button

### ISSUE THREAD

**Issue by calania** [eyal0/OctoPrint-PrintTimeGenius#99]
Hello I am really liking this plugin and the edition of the addition of the analyze while heating feature is great. But sometimes I allready have set the temp on the printer when I press start printing so your plugin doesn't have the time to analyze the file. Therefore I would really like a "analyze file now button" that ideally only is displayed when the file the printer is printing hasn't been analyzed. This button could be placed somewhere on the main page. Hope this is something that could be implemented and thanks for this plugin!

**Comment by calania** [comment]
Okay, maybe a button isn't the best. Any plans on adding a analyze while auto levelling? The plugin would probably just need to look for a G29 command and then it could analyze the file. Or maybe instead of adding a specific analyze while auto-levelling function it would maybe be better with having a box in the settings where the user could write any Gcode string and if the plugin sees this string it could analyze the file.

**Comment by eyal0** [comment]
G29 might not last long enough to do analysis. I used the end of heating as a signal that it's time to stop analysis. I'm not sure what a better signal would be. I'm wary of watching the gcode commands and using that because I've seen in the past that if I will code that runs for each gcode commands, it really slows down the printers.

**Comment by calania** [comment]
Okay, I understand that you can't make a good implementation then. But just a question, if I would enable "analyze while printing" and it Finnished analyzing whiles autoleveling that wouldn't make the print quality worse for me right?

**Comment by eyal0** [comment]
Correct. It's possible that you could analyze even while printing and it wouldn't affect quality. It just depends on the speed of your Raspberry Pi. Some people see stuttering while printing, some don't. Try it and find out.

**Comment by calania** [comment]
Okay think that that will solve it for me. Thanks for the help!
